# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Copy Files to Build Directory
        run: |
          echo Copy files to build directory running..
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          mkdir build
          cp -r "./Azure Functions/modules" build/modules
          cp host.json build/host.json
          cp profile.ps1 build/profile.ps1
          cp requirements.ps1 build/requirements.ps1
          cp -r SendClientEvent build/SendClientEvent
          cp -r SetSecret build/SetSecret
          cp -r MacEstablish build/MacEstablish

      - name: Zip Build Files
        run: |
          echo Zip Build Files running...
          cd $GITHUB_WORKSPACE/build
          zip -r function_artifact.zip *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          # Artifact name
          name: function_artifact # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: $GITHUB_WORKSPACE/build/function_artifact.zip
